"""Build a bounded grayscale glyph atlas; no font library is needed on the XZ."""
from pathlib import Path
import hashlib
import json
import math
from PIL import Image,ImageDraw,ImageFont

root=Path(__file__).resolve().parent
source=root/'BarlowSemiCondensed-Medium.ttf'
manifest=json.loads((root/'source.json').read_text())
if hashlib.sha256(source.read_bytes()).hexdigest()!=manifest['sha256'][source.name]:
    raise ValueError('Font source differs from its pinned digest')
data=[];tables=[]
for size in (12,20):
    font=ImageFont.truetype(str(source),size)
    baseline=-font.getbbox('H',anchor='ls')[1]
    glyphs=[]
    for code in range(32,256):
        char=chr(code) if code<127 or code>=160 else '?'
        x0,y0,x1,y1=font.getbbox(char,anchor='ls')
        width,height=x1-x0,y1-y0
        mask=Image.new('L',(max(1,width),max(1,height)))
        ImageDraw.Draw(mask).text((-x0,-y0),char,font=font,anchor='ls',fill=255)
        pixels=list(mask.tobytes()) if width and height else []
        glyphs.append((len(data),width,height,x0,y0+baseline,math.ceil(font.getlength(char))))
        data.extend(pixels)
    tables.append(glyphs)
lines=['/* Generated by fonts/generate.py. Glyph data: SIL-OFL-1.1; see fonts/OFL.txt. */',
       '#ifndef XZ_UI_FONT_ATLAS_H','#define XZ_UI_FONT_ATLAS_H','#include <stdint.h>',
       'struct xz_font_glyph { uint32_t offset; uint8_t width,height; int8_t x,y; uint8_t advance; };',
       'static const struct xz_font_glyph xz_font_glyphs[2][224] = {']
for table in tables:
    lines.append('{')
    lines.extend('{'+','.join(map(str,g))+'},' for g in table)
    lines.append('},')
lines.extend(['};','static const unsigned char xz_font_coverage[] = {'])
for i in range(0,len(data),32):lines.append(','.join(map(str,data[i:i+32]))+',')
lines.extend(['};','#endif',''])
(root.parent/'font_atlas.h').write_text('\n'.join(lines),encoding='ascii')
print(f'Generated two sizes, Latin-1 glyphs, {len(data)} coverage bytes')
